services:
  - type: web
    name: discord-music-bot
    env: python
    pythonVersion: "3.11.8"  # Most stable for voice
    plan: free
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y ffmpeg python3-dev
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        fromGroup: discord-bot-secrets
      - key: DISABLE_WEBSOCKET_COMPRESSION
        value: "true"
