services:
  - type: web
    name: discord-music-bot
    env: python
    pythonVersion: "3.11"  # Downgrade from 3.13
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y ffmpeg python3-dev
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        fromGroup: discord-bot-secrets
